site_name: Forge Documentation
pages:
  - [index.md, Home]
  - [styleguide.md, Style Guide]
  - [gettingstarted/index.md, Getting Started, Home]
  - [gettingstarted/structuring.md, Getting Started, Structuring Your Mod]
  - [blockstates/introduction.md, Models & Rendering, Blockstates]
  - [blockstates/forgeBlockstates.md, Models & Rendering, Blockstates, Forges Blockstates]
  - [networking/index.md, Networking, Home]
  - [networking/overview.md, Networking, Overview]
  - [networking/simpleimpl.md, Networking, SimpleImpl]
  - [conventions/versioning.md, Conventions, Versioning]
