site_name: Forge Documentation
pages:
  - Home: 'index.md'
  - Style Guide: 'styleguide.md'
  - Getting Started:
    - Home: 'gettingstarted/index.md'
    - Structuring Your Mod: 'gettingstarted/structuring.md'
  - Models & Rendering:
    - Blockstates: 'blockstates/introduction.md'
    - Forge Blockstates: 'blockstates/forgeBlockstates.md'
  - Networking:
    - Home: 'networking/index.md'
    - Overview: 'networking/overview.md'
    - SimpleImpl: 'networking/simpleimpl.md'
  - Conventions:
    - Versioning: 'conventions/versioning.md'
